const seedProducts=[
{id:1,name:'Idli',cat:'South Indian',price:45,variants:[['Plate',45]]},{id:2,name:'Vada',cat:'South Indian',price:50,variants:[['Plate',50]]},{id:3,name:'Idli Vada',cat:'South Indian',price:70,variants:[['Plate',70]]},{id:4,name:'Masala Dosa',cat:'South Indian',price:90,variants:[['Regular',90]]},{id:5,name:'Plain Dosa',cat:'South Indian',price:75,variants:[['Regular',75]]},{id:6,name:'Set Dosa',cat:'South Indian',price:85,variants:[['Plate',85]]},{id:7,name:'Rava Dosa',cat:'South Indian',price:100,variants:[['Regular',100]]},{id:8,name:'Mysore Masala Dosa',cat:'South Indian',price:110,variants:[['Regular',110]]},{id:9,name:'Onion Dosa',cat:'South Indian',price:105,variants:[['Regular',105]]},{id:10,name:'Pongal',cat:'Breakfast',price:80,variants:[['Half',50],['Full',80]]},{id:11,name:'Poori Sagu',cat:'Breakfast',price:90,variants:[['Plate',90]]},{id:12,name:'Upma',cat:'Breakfast',price:65,variants:[['Half',40],['Full',65]]},{id:13,name:'Veg Meals',cat:'Meals',price:160,variants:[['Half',110],['Full',160]]},{id:14,name:'South Indian Thali',cat:'Meals',price:190,variants:[['Full',190]]},{id:15,name:'Paneer Butter Masala',cat:'North Indian',price:210,variants:[['Half',135],['Full',210]]},{id:16,name:'Veg Kadai',cat:'North Indian',price:200,variants:[['Half',130],['Full',200]]},{id:17,name:'Dal Tadka',cat:'North Indian',price:170,variants:[['Half',110],['Full',170]]},{id:18,name:'Butter Naan',cat:'Breads',price:55,variants:[['Piece',55]]},{id:19,name:'Chapati',cat:'Breads',price:30,variants:[['Piece',30]]},{id:20,name:'Curd Rice',cat:'Rice',price:85,variants:[['Half',55],['Full',85]]},{id:21,name:'Veg Pulao',cat:'Rice',price:150,variants:[['Half',95],['Full',150]]},{id:22,name:'Lemon Rice',cat:'Rice',price:90,variants:[['Half',60],['Full',90]]},{id:23,name:'Filter Coffee',cat:'Beverages',price:45,variants:[['Regular',45]]},{id:24,name:'Tea',cat:'Beverages',price:30,variants:[['Regular',30]]},{id:25,name:'Fresh Lime Soda',cat:'Beverages',price:70,variants:[['Half',40],['Full',70]]},{id:26,name:'Mineral Water',cat:'Beverages',price:20,variants:[['500ml',20],['1L',30]]},{id:27,name:'Mango Lassi',cat:'Beverages',price:100,variants:[['Half',65],['Full',100]]},{id:28,name:'Gulab Jamun',cat:'Desserts',price:80,variants:[['2 pcs',80]]}
];
let products=JSON.parse(localStorage.getItem('varahi_products')||'null');
if(!products||products.some(p=>p.type==='Non-Veg')){products=seedProducts.map(p=>({...p,active:true}));localStorage.setItem('varahi_products',JSON.stringify(products));}
let cart=[],cat='Favorite Items',mode='DINE IN',payment='Cash',table='T01',billNo=21,search='';
const cats=['Favorite Items','Starters','Soups','Indian Breads','Meal Boxes','South Indian','Rice','Beverages','Desserts'];
const money=n=>'₹'+Number(n).toLocaleString('en-IN',{minimumFractionDigits:0});
const save=()=>localStorage.setItem('varahi_products',JSON.stringify(products));
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function render(){document.getElementById('app').innerHTML=`<div class="pos-shell"><header class="pos-head"><button class="hamb">☰</button><div class="vmark">V</div><b>Varahi Billing Software</b><div class="head-right"><button>◌ &nbsp;ASK FOR SUPPORT</button><span>◉</span><span>♧</span><span>◎</span></div></header><div class="pos-body"><aside class="left-nav">${cats.map(c=>`<button class="${cat===c?'sel':''}" onclick="setCat('${c}')">${c}</button>`).join('')}<button class="manage" onclick="menuManage()">⚙ Menu Management</button></aside><main class="items-area"><div class="search"><span>⌕</span><input placeholder="Search item" value="${esc(search)}" oninput="search=this.value;drawItems()"></div><div class="item-grid" id="item-grid">${items()}</div></main><section class="order-area"><div class="order-tabs">${['DINE IN','DELIVERY','PICK UP'].map(x=>`<button class="${mode===x?'active':''}" onclick="mode='${x}';render()">${x}</button>`).join('')}</div><div class="order-tools"><button onclick="chooseTable()">⌖</button><button onclick="chooseGuests()">♟</button><button onclick="chooseGuests()">♟♟</button><span>Bill No. <b>${billNo}</b></span></div><div class="order-label"><span>ITEMS</span><span>CHECKITEMS</span><span>QTY.</span><span>PRICE</span></div><div class="cart" id="cart">${cartHtml()}</div><div class="bill-bottom"><div class="total-row"><span>Total</span><b>${money(total())}</b></div><div class="pay-row">${['Cash','Card','Due','Part'].map(x=>`<label><input type="radio" name="pay" ${payment===x?'checked':''} onchange="payment='${x}'"> ${x}</label>`).join('')}</div><div class="paid"><label><input type="checkbox"> It's Paid</label></div><div class="bill-actions"><button onclick="newBill()">SAVE</button><button onclick="printBill()">SAVE & PRINT</button><button onclick="kot()">KOT</button><button onclick="kot();printBill()">KOT & PRINT</button></div></div></section></div></div><div id="modal"></div>`;}
function items(){let arr=products.filter(p=>p.active);if(cat==='South Indian')arr=arr.filter(p=>p.cat==='South Indian');else if(cat==='Beverages')arr=arr.filter(p=>p.cat==='Beverages');else if(cat==='Indian Breads')arr=arr.filter(p=>p.cat==='Breads');else if(cat==='Rice')arr=arr.filter(p=>p.cat==='Rice');else if(cat==='Desserts')arr=arr.filter(p=>p.cat==='Desserts');else if(cat==='Starters'||cat==='Soups'||cat==='Meal Boxes')arr=arr.filter(p=>p.cat===cat);else if(cat==='Favorite Items')arr=arr.slice(0,18);if(search)arr=arr.filter(p=>p.name.toLowerCase().includes(search.toLowerCase()));return arr.map(p=>`<button class="item" onclick="variants(${p.id})"><span class="veg-mark">●</span><strong>${esc(p.name)}</strong><small>₹${Math.min(...p.variants.map(v=>v[1]))}</small></button>`).join('')||'<div class="no-items">No items found</div>';}
function drawItems(){const g=document.getElementById('item-grid');if(g)g.innerHTML=items();}
function setCat(x){cat=x;search='';render();}
function variants(id){const p=products.find(x=>x.id===id);document.getElementById('modal').innerHTML=`<div class="shade" onclick="closeModal()"><div class="choice" onclick="event.stopPropagation()"><h3>${esc(p.name)}</h3><p>Select portion / size</p>${p.variants.map((v,i)=>`<button onclick="add(${p.id},${i})"><span>${esc(v[0])}</span><b>${money(v[1])}</b></button>`).join('')}<button class="close" onclick="closeModal()">Cancel</button></div></div>`;}
function add(id,i){const p=products.find(x=>x.id===id),v=p.variants[i],f=cart.find(x=>x.id===id&&x.variant===v[0]);if(f)f.qty++;else cart.push({id:p.id,name:p.name,variant:v[0],price:v[1],qty:1});closeModal();render();}
function cartHtml(){if(!cart.length)return '<div class="empty-cart">No Item Selected<br><small>Please Select Item from Left Menu Item</small><div class="plate">♨</div></div>';return cart.map((x,i)=>`<div class="cart-line"><div><b>${esc(x.name)}</b><small>${esc(x.variant)}</small></div><div class="qty"><button onclick="qty(${i},-1)">−</button><b>${x.qty}</b><button onclick="qty(${i},1)">+</button></div><strong>${money(x.price*x.qty)}</strong></div>`).join('');}
function qty(i,n){cart[i].qty+=n;if(cart[i].qty<1)cart.splice(i,1);render();}
function total(){return cart.reduce((s,x)=>s+x.price*x.qty,0);}
function newBill(){cart=[];billNo++;mode='DINE IN';render();}
function chooseTable(){const t=prompt('Enter table number',table);if(t){table=t.toUpperCase();render();}}
function chooseGuests(){prompt('Number of guests','2');}
function closeModal(){document.getElementById('modal').innerHTML='';}
function kot(){if(!cart.length)return alert('Add items before sending KOT.');alert(`KOT #${billNo} sent to kitchen for ${mode==='DINE IN'?table:mode}.`);}
function printBill(){if(!cart.length)return alert('Add items before printing.');const rows=cart.map(x=>`<div>${esc(x.name)} ${esc(x.variant)} x${x.qty}<b>${money(x.price*x.qty)}</b></div>`).join('');document.getElementById('modal').innerHTML=`<div class="shade"><div class="receipt"><h2>VARAHI BILLING SOFTWARE</h2><p>**** · ****</p><hr>${rows}<hr><h3>TOTAL <b>${money(total())}</b></h3><p>${mode==='DINE IN'?`Table ${table} · `:''}${payment}</p><p>Thank you for visiting</p><button onclick="window.print()">PRINT THERMAL BILL</button><button onclick="closeModal()">CLOSE</button></div></div>`;}
function menuManage(){document.getElementById('modal').innerHTML=`<div class="shade"><div class="manager"><h2>Menu Management</h2><p>Add, edit or delete vegetarian restaurant items.</p><button class="add-product" onclick="addProductForm()">＋ Add Product</button><div class="product-list">${products.map(p=>`<div><span class="veg-mark">●</span><b>${esc(p.name)}</b><small>${esc(p.cat)} · ${money(p.price)}</small><button onclick="editProduct(${p.id})">Edit</button><button onclick="deleteProduct(${p.id})">Delete</button></div>`).join('')}</div><button class="close" onclick="closeModal()">Close</button></div></div>`;}
function addProductForm(id){const p=id?products.find(x=>x.id===id):{name:'',cat:'South Indian',price:'',variants:[['Regular','']]};document.getElementById('modal').innerHTML=`<div class="shade"><div class="form"><h2>${id?'Edit':'Add'} Product</h2><label>Name<input id="pn" value="${esc(p.name)}"></label><label>Category<select id="pc">${['South Indian','Breakfast','Meals','North Indian','Breads','Rice','Beverages','Desserts','Starters','Soups'].map(c=>`<option ${c===p.cat?'selected':''}>${c}</option>`).join('')}</select></label><label>Portion name<input id="pv" value="${esc(p.variants[0]?.[0]||'Regular')}"></label><label>Price<input id="pp" type="number" value="${p.variants[0]?.[1]||p.price||''}"></label><button onclick="saveProduct(${id||0})">Save Product</button><button class="close" onclick="menuManage()">Cancel</button></div></div>`;}
function saveProduct(id){const name=document.getElementById('pn').value.trim(),cat=document.getElementById('pc').value,v=document.getElementById('pv').value.trim(),price=Number(document.getElementById('pp').value);if(!name||!v||!price)return alert('Enter product, portion and price.');if(id){const p=products.find(x=>x.id===id);Object.assign(p,{name,cat,price,variants:[[v,price]],active:true});}else products.push({id:Date.now(),name,cat,price,variants:[[v,price]],active:true});save();menuManage();}
function editProduct(id){addProductForm(id)}
function deleteProduct(id){if(confirm('Delete this product?')){products=products.filter(p=>p.id!==id);save();menuManage();}}
render();
