const seedProducts = [
  {id:1,name:'Chicken Biryani',category:'Rice & Biryani',type:'Non-Veg',price:260,variants:[['Half',180],['Full',260]],active:true},
  {id:2,name:'Mutton Biryani',category:'Rice & Biryani',type:'Non-Veg',price:340,variants:[['Half',230],['Full',340]],active:true},
  {id:3,name:'Chicken 65',category:'Starters',type:'Non-Veg',price:190,variants:[['Half',110],['Full',190]],active:true},
  {id:4,name:'Butter Chicken',category:'Main Course',type:'Non-Veg',price:280,variants:[['Half',180],['Full',280]],active:true},
  {id:5,name:'Fish Fry',category:'Starters',type:'Non-Veg',price:220,variants:[['Piece',120],['Plate',220]],active:true},
  {id:6,name:'Paneer Butter Masala',category:'Main Course',type:'Veg',price:220,variants:[['Half',140],['Full',220]],active:true},
  {id:7,name:'Masala Dosa',category:'South Indian',type:'Veg',price:90,variants:[['Regular',90]],active:true},
  {id:8,name:'Idli Vada',category:'South Indian',type:'Veg',price:90,variants:[['Plate',90]],active:true},
  {id:9,name:'Butter Naan',category:'Breads',type:'Veg',price:60,variants:[['Piece',60]],active:true},
  {id:10,name:'Tandoori Roti',category:'Breads',type:'Veg',price:35,variants:[['Piece',35]],active:true},
  {id:11,name:'Fresh Lime Soda',category:'Beverages',type:'Veg',price:70,variants:[['Half',40],['Full',70]],active:true},
  {id:12,name:'Mineral Water',category:'Beverages',type:'Veg',price:20,variants:[['500ml',20],['1L',30]],active:true},
  {id:13,name:'Mango Lassi',category:'Beverages',type:'Veg',price:110,variants:[['Half',70],['Full',110]],active:true},
  {id:14,name:'Gulab Jamun',category:'Desserts',type:'Veg',price:90,variants:[['2 pcs',90]],active:true}
];
let products = JSON.parse(localStorage.getItem('varahi_products') || 'null') || seedProducts;
let cart=[]; let category='All'; let foodType='All'; let mode='Dine-in'; let payment='Cash'; let page='pos'; let table='T1'; let search=''; let orderNote='';
const categories=['All','Rice & Biryani','Starters','Main Course','South Indian','Breads','Beverages','Desserts'];
const money=n=>'₹'+Number(n).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
const save=()=>localStorage.setItem('varahi_products',JSON.stringify(products));
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function render(){document.getElementById('app').innerHTML=`
<header class="topbar"><div class="brand"><div class="logo">V</div><div><h1>Varahi Billing Software</h1><small>Restaurant POS & Billing</small></div></div><div class="top-actions"><span class="live-dot"></span><span class="shift">Shift: General</span><button class="ghost" onclick="openReceipt()">Preview Bill</button><button class="primary" onclick="newOrder()">New Bill</button></div></header>
<div class="layout"><aside class="sidebar"><div class="outlet"><span>OUTLET</span><b>****</b><small>****</small></div><nav class="nav">${[['pos','▣','POS / Billing'],['tables','▦','Tables'],['kitchen','♨','Kitchen / KOT'],['reports','▤','Reports'],['menu','☷','Menu'],['settings','⚙','Settings']].map(x=>`<button class="${page===x[0]?'active':''}" onclick="navigate('${x[0]}')"><i>${x[1]}</i><span>${x[2]}</span></button>`).join('')}</nav><div class="sidebar-foot">Varahi Billing Software<br><small>Demo environment</small></div></aside><main class="main">${pageContent()}</main></div><div id="modal" class="modal" onclick="if(event.target.id==='modal')closeModal()"></div>`;}
function pageContent(){if(page==='pos')return posPage();if(page==='tables')return tablesPage();if(page==='kitchen')return kitchenPage();if(page==='reports')return reportsPage();if(page==='menu')return menuPage();return settingsPage();}
function posPage(){const t=totals();return `<div class="page-head"><div><div class="eyebrow">SALES COUNTER</div><h2>Point of Sale</h2><p>Take an order, send it to kitchen and settle the bill.</p></div><div class="head-meta"><span>Bill #VS-${String(Date.now()).slice(-5)}</span><span>Business: ****</span></div></div><div class="stats"><div class="stat"><span>Today's Sales</span><strong>₹24,680</strong><small>+8.4% vs yesterday</small></div><div class="stat"><span>Orders Today</span><strong>86</strong><small>12 open orders</small></div><div class="stat"><span>Tables</span><strong>12 / 20</strong><small>8 currently occupied</small></div><div class="stat"><span>Average Bill</span><strong>₹287</strong><small>Last 30 orders</small></div></div><div class="workspace"><section class="panel menu-panel"><div class="toolbar"><div class="searchbox"><span>⌕</span><input value="${escapeHtml(search)}" placeholder="Search dishes, drinks..." oninput="setSearch(this.value)"></div><div class="food-toggle">${['All','Veg','Non-Veg'].map(x=>`<button class="${foodType===x?'active':''}" onclick="setFoodType('${x}')">${x==='Veg'?'● ':x==='Non-Veg'?'● ':''}${x}</button>`).join('')}</div></div><div class="category-strip">${categories.map(c=>`<button class="filter ${category===c?'active':''}" onclick="setCategory('${c}')">${c}</button>`).join('')}</div><div class="menu">${renderMenu()}</div></section><section class="panel order-panel"><div class="order-head"><div><span class="eyebrow">CURRENT ORDER</span><h3>${mode==='Dine-in'?`Table ${table}`:mode}</h3></div><button class="clear" onclick="clearCart()">Clear</button></div><div class="order-modes">${['Dine-in','Takeaway','Delivery'].map(x=>`<button class="${mode===x?'active':''}" onclick="setMode('${x}')">${x}</button>`).join('')}</div>${mode==='Dine-in'?`<div class="table-row">${Array.from({length:8},(_,i)=>`<button class="table ${table==='T'+(i+1)?'active':''}" onclick="table='T${i+1}';render()">T${i+1}</button>`).join('')}</div>`:''}<div class="cart-items">${renderCart()}</div><button class="note-btn" onclick="addOrderNote()">＋ Add order note ${orderNote?`<span>• ${escapeHtml(orderNote)}</span>`:''}</button><div class="summary"><div class="line"><span>Subtotal</span><b>${money(t.subtotal)}</b></div><div class="line"><span>Discount</span><span class="discount">${t.discount?'- '+money(t.discount):'₹0.00'}</span></div><div class="line"><span>GST</span><span>${money(t.tax)}</span></div><div class="line total"><span>Grand Total</span><strong>${money(t.total)}</strong></div></div><div class="payment-label">PAYMENT</div><div class="pay-grid">${['Cash','UPI','Card'].map(x=>`<button class="${payment===x?'active':''}" onclick="payment='${x}';render()">${x}</button>`).join('')}</div><button class="checkout" onclick="checkout()">Charge ${money(t.total)} <span>→</span></button></section></div>`;}
function filteredProducts(){return products.filter(x=>x.active && (category==='All'||x.category===category)&&(foodType==='All'||x.type===foodType)&&x.name.toLowerCase().includes(search.toLowerCase()));}
function renderMenu(){const list=filteredProducts();if(!list.length)return '<div class="empty-menu">No matching items.<br><small>Try another category or search.</small></div>';return list.map(x=>`<button class="item" onclick="openVariant(${x.id})"><div class="item-top"><span class="food-dot ${x.type==='Veg'?'veg':'nonveg'}"></span><span class="item-category">${escapeHtml(x.category)}</span></div><div class="item-icon">${iconFor(x.category)}</div><div class="item-name">${escapeHtml(x.name)}</div><div class="item-bottom"><span>from ${money(Math.min(...x.variants.map(v=>v[1])))}</span><span class="choose">Choose ›</span></div></button>`).join('');}
function iconFor(c){return ({'Rice & Biryani':'🍚','Starters':'🍢','Main Course':'🍲','South Indian':'🥞','Breads':'🫓','Beverages':'🥤','Desserts':'🍮'})[c]||'🍽️';}
function renderCart(){if(!cart.length)return '<div class="empty">Your order is empty.<br><small>Select an item from the menu to begin.</small></div>';return cart.map((x,i)=>`<div class="cart-row"><div class="cart-main"><div class="cart-title">${escapeHtml(x.name)}</div><div class="cart-variant">${escapeHtml(x.variant)}${x.note?` · ${escapeHtml(x.note)}`:''}</div><div class="qty-controls"><button onclick="changeQty(${i},-1)">−</button><b>${x.qty}</b><button onclick="changeQty(${i},1)">+</button></div></div><div class="cart-price">${money(x.price*x.qty)}<button onclick="removeCart(${i})">×</button></div></div>`).join('');}
function totals(){const subtotal=cart.reduce((s,x)=>s+x.price*x.qty,0);const discount=subtotal>=1500?Math.round(subtotal*.05):0;const tax=Math.round((subtotal-discount)*.05);return {subtotal,discount,tax,total:subtotal-discount+tax};}
function openVariant(id){const p=products.find(x=>x.id===id);document.getElementById('modal').className='modal show';document.getElementById('modal').innerHTML=`<div class="dialog small"><div class="dialog-head"><div><span class="eyebrow">ADD TO ORDER</span><h3>${escapeHtml(p.name)}</h3></div><button onclick="closeModal()">×</button></div><div class="variant-list">${p.variants.map((v,i)=>`<button onclick="addProduct(${p.id},${i})"><span><b>${escapeHtml(v[0])}</b><small>${p.type} · ${p.category}</small></span><strong>${money(v[1])}</strong><span>＋</span></button>`).join('')}</div><div class="dialog-foot">Select portion/size before adding. Prices are configured per restaurant.</div></div>`;}
function addProduct(id,variantIndex){const p=products.find(x=>x.id===id);const v=p.variants[variantIndex];const found=cart.find(x=>x.id===id&&x.variant===v[0]);if(found)found.qty++;else cart.push({id,name:p.name,variant:v[0],price:v[1],qty:1});closeModal();render();}
function changeQty(i,n){cart[i].qty+=n;if(cart[i].qty<=0)cart.splice(i,1);render();}
function removeCart(i){cart.splice(i,1);render();}
function clearCart(){if(cart.length&&confirm('Clear this order?')){cart=[];orderNote='';render();}}
function addOrderNote(){const n=prompt('Order note / kitchen instruction:',orderNote);if(n!==null){orderNote=n.trim();render();}}
function setCategory(c){category=c;render()}function setFoodType(x){foodType=x;render()}function setMode(x){mode=x;render()}function setSearch(x){search=x;const m=document.getElementById('menu');if(m)m.innerHTML=renderMenu();}
function navigate(p){page=p;render()}function newOrder(){cart=[];orderNote='';mode='Dine-in';table='T1';navigate('pos');}
function checkout(){if(!cart.length){alert('Add items before charging the bill.');return}openReceipt();}
function openReceipt(){const fallback=!cart.length;const rows=fallback?[{name:'Chicken Biryani',variant:'Full',price:260,qty:1},{name:'Fresh Lime Soda',variant:'Full',price:70,qty:2}]:cart;const t=fallback?{subtotal:400,discount:0,tax:20,total:420}:totals();document.getElementById('modal').className='modal show';document.getElementById('modal').innerHTML=`<div class="receipt-wrap"><div class="receipt"><div class="receipt-brand"><div class="logo small-logo">V</div><div><b>VARAHI BILLING SOFTWARE</b><small>Restaurant POS</small></div></div><div class="receipt-contact">**** · ****</div><hr>${rows.map(x=>`<div class="receipt-row"><span>${escapeHtml(x.name)}<small>${escapeHtml(x.variant)} × ${x.qty}</small></span><b>${money(x.price*x.qty)}</b></div>`).join('')}<hr><div class="receipt-row"><span>Subtotal</span><span>${money(t.subtotal)}</span></div><div class="receipt-row"><span>Discount</span><span>- ${money(t.discount)}</span></div><div class="receipt-row"><span>GST 5%</span><span>${money(t.tax)}</span></div><div class="receipt-row grand"><span>TOTAL</span><b>${money(t.total)}</b></div><div class="receipt-row"><span>Payment</span><b>${payment}</b></div><div class="receipt-foot">${mode==='Dine-in'?`Table ${table} · `:''}${new Date().toLocaleString('en-IN')}<br>Thank you for visiting.</div></div><div class="receipt-actions"><button class="secondary" onclick="closeModal()">Back</button><button class="primary" onclick="window.print()">Print Thermal Bill</button></div></div>`;}
function closeModal(){const m=document.getElementById('modal');m.className='modal';m.innerHTML='';}
function tablesPage(){return `<div class="page-head"><div><div class="eyebrow">FLOOR</div><h2>Tables</h2><p>See occupied, available and billing tables at a glance.</p></div><button class="primary" onclick="newOrder()">＋ New Order</button></div><div class="floor-legend"><span><i class="legend green"></i>Available</span><span><i class="legend amber"></i>Occupied</span><span><i class="legend blue"></i>Billing</span></div><div class="table-grid">${Array.from({length:20},(_,i)=>{const n=i+1,status=n%5===0?'Billing':n%3===0?'Available':'Occupied';return `<div class="table-card ${status.toLowerCase()}"><div class="table-card-head"><b>Table ${n}</b><span>${status}</span></div><div class="table-number">${String(n).padStart(2,'0')}</div><p>${status==='Available'?'Ready for seating':status==='Billing'?'Bill being settled':`${(n%4)+1} guests · ₹${(n*280).toLocaleString('en-IN')}`}</p><button onclick="table='T${n}';navigate('pos')">${status==='Available'?'Open Table':'View Order'} →</button></div>`}).join('')}</div>`;}
function kitchenPage(){const orders=[['KOT #1021','T04','Chicken Biryani × 2, Naan × 3','Preparing'],['KOT #1022','T02','Masala Dosa × 2, Lime Soda × 2','Ready'],['KOT #1023','Takeaway','Mutton Biryani × 1, Chicken 65 × 1','New'],['KOT #1024','T07','Fish Fry × 2, Butter Chicken × 1','Preparing']];return `<div class="page-head"><div><div class="eyebrow">KITCHEN</div><h2>Kitchen Display</h2><p>Keep KOTs moving without losing track of the floor.</p></div><span class="badge">4 Active KOTs</span></div><div class="kot-board">${orders.map((o,i)=>`<div class="kot-card"><div class="kot-top"><b>${o[0]}</b><span class="status ${o[3].toLowerCase()}">${o[3]}</span></div><div class="kot-table">${o[1]}</div><p>${o[2]}</p><div class="kot-actions"><small>${i+2} min ago</small><button onclick="alert('${o[0]} marked ready')">Mark Ready</button></div></div>`).join('')}</div>`;}
function reportsPage(){return `<div class="page-head"><div><div class="eyebrow">BUSINESS</div><h2>Reports</h2><p>Quick numbers for today's operation.</p></div><button class="secondary">Today ▾</button></div><div class="stats"><div class="stat"><span>Gross Sales</span><strong>₹24,680</strong><small>86 bills</small></div><div class="stat"><span>Cash</span><strong>₹8,420</strong><small>34% of sales</small></div><div class="stat"><span>UPI</span><strong>₹11,280</strong><small>46% of sales</small></div><div class="stat"><span>Card</span><strong>₹4,980</strong><small>20% of sales</small></div></div><div class="report-grid"><div class="card"><div class="card-title"><h3>Sales by Category</h3><span>Today</span></div>${[['Rice & Biryani',82],['Main Course',65],['Starters',52],['Beverages',36],['South Indian',29]].map(x=>`<div class="bar-row"><div><span>${x[0]}</span><b>${x[1]}%</b></div><div class="bar"><span style="width:${x[1]}%"></span></div></div>`).join('')}</div><div class="card"><div class="card-title"><h3>Order Mix</h3></div>${[['Dine-in','58%'],['Takeaway','27%'],['Delivery','15%']].map(x=>`<div class="line"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div></div>`;}
function menuPage(){return `<div class="page-head"><div><div class="eyebrow">CATALOG</div><h2>Menu Management</h2><p>Add dishes, manage portions and keep prices under control.</p></div><button class="primary" onclick="openProductForm()">＋ Add Product</button></div><div class="menu-tools"><div class="searchbox"><span>⌕</span><input placeholder="Search products..." oninput="renderProductTable(this.value)"></div><span>${products.length} products</span></div><div class="card table-card-list"><table><thead><tr><th>Item</th><th>Type</th><th>Category</th><th>Portions</th><th>Price From</th><th>Status</th><th></th></tr></thead><tbody id="product-table">${productRows()}</tbody></table></div>`;}
function productRows(q=''){return products.filter(p=>p.name.toLowerCase().includes(q.toLowerCase())).map(p=>`<tr><td><div class="product-name"><span class="food-dot ${p.type==='Veg'?'veg':'nonveg'}"></span><b>${escapeHtml(p.name)}</b></div></td><td>${p.type}</td><td>${escapeHtml(p.category)}</td><td>${p.variants.map(v=>`${escapeHtml(v[0])} ${money(v[1])}`).join(' · ')}</td><td>${money(Math.min(...p.variants.map(v=>v[1])))}</td><td><span class="status active">${p.active?'Active':'Hidden'}</span></td><td><button class="icon-btn" onclick="openProductForm(${p.id})">Edit</button> <button class="icon-btn danger-text" onclick="deleteProduct(${p.id})">Delete</button></td></tr>`).join('');}
function renderProductTable(q){const el=document.getElementById('product-table');if(el)el.innerHTML=productRows(q);}
function openProductForm(id=null){const p=id?products.find(x=>x.id===id):{name:'',category:'Main Course',type:'Veg',price:'',variants:[['Half',''],['Full','']],active:true};document.getElementById('modal').className='modal show';document.getElementById('modal').innerHTML=`<div class="dialog"><div class="dialog-head"><div><span class="eyebrow">MENU SETUP</span><h3>${id?'Edit Product':'Add Product'}</h3></div><button onclick="closeModal()">×</button></div><div class="form-grid"><label>Product Name<input id="p-name" value="${escapeHtml(p.name)}"></label><label>Category<select id="p-category">${categories.filter(c=>c!=='All').map(c=>`<option ${c===p.category?'selected':''}>${c}</option>`).join('')}</select></label><label>Food Type<select id="p-type"><option ${p.type==='Veg'?'selected':''}>Veg</option><option ${p.type==='Non-Veg'?'selected':''}>Non-Veg</option></select></label><label>Default Price<input id="p-price" type="number" value="${p.price}"></label></div><div class="variant-editor"><div class="variant-editor-head"><b>Portions / Sizes</b><button class="link-btn" onclick="addVariantField()">＋ Add portion</button></div><div id="variant-fields">${p.variants.map(v=>variantField(v[0],v[1])).join('')}</div></div><div class="dialog-foot">Examples: Half / Full, 500ml / 1L, Piece / Plate. Restaurant pricing stays editable.</div><div class="dialog-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" onclick="saveProduct(${id||'null'})">Save Product</button></div></div>`;}
function variantField(name='',price=''){return `<div class="variant-field"><input class="v-name" placeholder="Portion name" value="${escapeHtml(name)}"><input class="v-price" type="number" placeholder="Price" value="${price}"><button onclick="this.parentElement.remove()">×</button></div>`;}
function addVariantField(){document.getElementById('variant-fields').insertAdjacentHTML('beforeend',variantField());}
function saveProduct(id){const name=document.getElementById('p-name').value.trim();const category=document.getElementById('p-category').value;const type=document.getElementById('p-type').value;const price=Number(document.getElementById('p-price').value);const variants=[...document.querySelectorAll('.variant-field')].map(r=>[r.querySelector('.v-name').value.trim(),Number(r.querySelector('.v-price').value)]).filter(v=>v[0]&&v[1]>0);if(!name||!price||!variants.length){alert('Enter product name, price and at least one valid portion.');return}if(id){const p=products.find(x=>x.id===id);Object.assign(p,{name,category,type,price,variants});}else products.push({id:Date.now(),name,category,type,price,variants,active:true});save();closeModal();render();}
function deleteProduct(id){const p=products.find(x=>x.id===id);if(!p)return;if(confirm(`Delete ${p.name}?`)){products=products.filter(x=>x.id!==id);save();render();}}
function settingsPage(){return `<div class="page-head"><div><div class="eyebrow">SETUP</div><h2>Restaurant Settings</h2><p>Demo business profile and receipt configuration.</p></div></div><div class="settings-grid"><div class="card"><h3>Business Profile</h3><div class="setting-row"><span>Software</span><b>Varahi Billing Software</b></div><div class="setting-row"><span>Address</span><b>****</b></div><div class="setting-row"><span>Phone</span><b>****</b></div><div class="setting-row"><span>GSTIN</span><b>****</b></div></div><div class="card"><h3>Receipt & Billing</h3><div class="setting-row"><span>Paper</span><b>80mm Thermal</b></div><div class="setting-row"><span>Tax</span><b>GST 5%</b></div><div class="setting-row"><span>Currency</span><b>INR (₹)</b></div><div class="setting-row"><span>Order Types</span><b>Dine-in · Takeaway · Delivery</b></div></div></div>`;}
render();
