const seedProducts=[
{id:1,name:'Idli',cat:'South Indian',price:45,variants:[['Plate',45]],addons:['Extra Sambar','Extra Chutney'],active:true},
{id:2,name:'Vada',cat:'South Indian',price:50,variants:[['Plate',50]],addons:['Extra Sambar','Extra Chutney'],active:true},
{id:3,name:'Idli Vada',cat:'South Indian',price:70,variants:[['Plate',70]],addons:['Extra Sambar','Extra Chutney'],active:true},
{id:4,name:'Masala Dosa',cat:'South Indian',price:90,variants:[['Regular',90]],addons:['Extra Ghee','Extra Masala','Extra Sambar','Extra Chutney'],active:true},
{id:5,name:'Plain Dosa',cat:'South Indian',price:75,variants:[['Regular',75]],addons:['Extra Ghee','Extra Sambar','Extra Chutney'],active:true},
{id:6,name:'Set Dosa',cat:'South Indian',price:85,variants:[['3 Dosa',85]],addons:['Extra Ghee','Extra Sambar','Extra Chutney'],active:true},
{id:7,name:'Rava Dosa',cat:'South Indian',price:100,variants:[['Regular',100]],addons:['Extra Ghee','Extra Sambar','Extra Chutney'],active:true},
{id:8,name:'Mysore Masala Dosa',cat:'South Indian',price:110,variants:[['Regular',110]],addons:['Extra Ghee','Extra Masala','Extra Sambar'],active:true},
{id:9,name:'Onion Dosa',cat:'South Indian',price:105,variants:[['Regular',105]],addons:['Extra Ghee','Extra Sambar','Extra Chutney'],active:true},
{id:10,name:'Pongal',cat:'Breakfast',price:80,variants:[['Half',50],['Full',80]],addons:['Extra Ghee','Extra Sambar','Extra Chutney'],active:true},
{id:11,name:'Poori Sagu',cat:'Breakfast',price:90,variants:[['Plate',90]],addons:['Extra Poori'],active:true},
{id:12,name:'Upma',cat:'Breakfast',price:65,variants:[['Half',40],['Full',65]],addons:['Extra Coconut Chutney'],active:true},
{id:13,name:'Veg Meals',cat:'Meals',price:160,variants:[['Half',110],['Full',160]],addons:['Extra Rice','Extra Curd'],active:true},
{id:14,name:'South Indian Thali',cat:'Meals',price:190,variants:[['Full',190]],addons:['Extra Sweet'],active:true},
{id:15,name:'Paneer Butter Masala',cat:'North Indian',price:210,variants:[['Half',135],['Full',210]],addons:['Extra Gravy','Extra Butter'],active:true},
{id:16,name:'Veg Kadai',cat:'North Indian',price:200,variants:[['Half',130],['Full',200]],addons:['Extra Gravy'],active:true},
{id:17,name:'Dal Tadka',cat:'North Indian',price:170,variants:[['Half',110],['Full',170]],addons:['Extra Ghee'],active:true},
{id:18,name:'Butter Naan',cat:'Breads',price:55,variants:[['Piece',55]],addons:['Extra Butter'],active:true},
{id:19,name:'Chapati',cat:'Breads',price:30,variants:[['Piece',30]],addons:['Extra Ghee'],active:true},
{id:20,name:'Curd Rice',cat:'Rice',price:85,variants:[['Half',55],['Full',85]],addons:['Extra Curd'],active:true},
{id:21,name:'Veg Pulao',cat:'Rice',price:150,variants:[['Half',95],['Full',150]],addons:['Extra Raita'],active:true},
{id:22,name:'Lemon Rice',cat:'Rice',price:90,variants:[['Half',60],['Full',90]],addons:['Extra Chutney'],active:true},
{id:23,name:'Filter Coffee',cat:'Beverages',price:45,variants:[['Regular',45]],addons:['Extra Strong'],active:true},
{id:24,name:'Tea',cat:'Beverages',price:30,variants:[['Regular',30]],addons:['Less Sugar'],active:true},
{id:25,name:'Fresh Lime Soda',cat:'Beverages',price:70,variants:[['Half',40],['Full',70]],addons:['Salt','Sweet'],active:true},
{id:26,name:'Mineral Water',cat:'Beverages',price:20,variants:[['500ml',20],['1L',30]],addons:[],active:true},
{id:27,name:'Mango Lassi',cat:'Beverages',price:100,variants:[['Half',65],['Full',100]],addons:['Less Sugar'],active:true},
{id:28,name:'Gulab Jamun',cat:'Desserts',price:80,variants:[['2 pcs',80]],addons:['Extra Sweet'],active:true}
];
let products=JSON.parse(localStorage.getItem('varahi_products')||'null');
if(!products||products.some(p=>p.type==='Non-Veg')){products=seedProducts;localStorage.setItem('varahi_products',JSON.stringify(products));}
let state={view:'pos',cat:'Favorite Items',mode:'DINE IN',payment:'Cash',table:'T01',billNo:Number(localStorage.getItem('varahi_bill')||21),search:'',cart:[],discount:0,coupon:'',customer:null,drawerOpen:false,offline:false,area:'Main Hall'};
const cats=['Favorite Items','Starters','Soups','Indian Breads','Meal Boxes','South Indian','Rice','Beverages','Desserts'];
const modules=[['dashboard','Dashboard','▦'],['pos','Orders & Billing','▣'],['tables','Tables','⌗'],['menu','Menu','☷'],['inventory','Inventory','▥'],['crm','CRM','♙'],['accounting','Accounting','₹'],['reports','Reports','▤'],['config','Configuration','⚙'],['users','User Management','♙'],['online','Online Orders','◉'],['kitchen','Kitchen / KOT','♨']];
const money=n=>'₹'+Number(n).toLocaleString('en-IN',{minimumFractionDigits:0});
const save=()=>localStorage.setItem('varahi_products',JSON.stringify(products));
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const idKey=()=>`${Date.now()}_${Math.random().toString(16).slice(2)}`;
function render(){document.getElementById('app').innerHTML=`<div class="pos-shell"><header class="pos-head"><button class="hamb" onclick="toggleDrawer()">☰</button><div class="brand-mark">V</div><div class="brand-name"><b>Varahi Billing Software</b><small>Restaurant POS</small></div><div class="head-location">**** ▾</div><div class="head-right"><span class="connection ${state.offline?'offline':''}">● ${state.offline?'OFFLINE MODE':'ONLINE'}</span><button onclick="showSupport()">◌ ASK FOR SUPPORT</button><span>◉</span><span>♧</span><span>◎</span></div></header>${state.view==='pos'?posView():moduleView(state.view)}${state.drawerOpen?drawer():''}<div id="modal"></div></div>`;}
function toggleDrawer(){state.drawerOpen=!state.drawerOpen;render();}
function drawer(){return `<div class="drawer-shade" onclick="toggleDrawer()"><aside class="module-drawer" onclick="event.stopPropagation()"><div class="drawer-title"><div><span class="eyebrow">VARAHI</span><h2>Restaurant Control</h2></div><button onclick="toggleDrawer()">×</button></div>${modules.map(m=>`<button class="module-link ${state.view===m[0]?'active':''}" onclick="goModule('${m[0]}')"><span class="module-icon">${m[2]}</span><span>${m[1]}</span><span class="chev">›</span></button>`).join('')}<div class="drawer-foot"><b>Outlet</b><span>****</span><small>Phone: ****</small></div></aside></div>`;}
function goModule(v){state.view=v;state.drawerOpen=false;render();}
function posView(){return `<div class="pos-body"><aside class="left-nav">${cats.map(c=>`<button class="${state.cat===c?'sel':''}" onclick="setCat('${c}')">${c}</button>`).join('')}<button class="manage" onclick="goModule('menu')">⚙ Menu Management</button></aside><main class="items-area"><div class="pos-toolbar"><div class="search"><span>⌕</span><input placeholder="Search item" value="${esc(state.search)}" oninput="state.search=this.value;drawItems()"></div><div class="quick-tools"><button onclick="showQR()">QR ORDER</button><button onclick="newBill()">NEW BILL</button></div></div><div class="item-grid" id="item-grid">${items()}</div></main><section class="order-area"><div class="order-tabs">${['DINE IN','DELIVERY','PICK UP'].map(x=>`<button class="${state.mode===x?'active':''}" onclick="setMode('${x}')">${x}</button>`).join('')}</div><div class="order-tools"><button onclick="chooseTable()">⌖</button><button onclick="chooseGuests()">♟</button><button onclick="customerModal()">♙</button><button onclick="splitMerge()">↔</button><span>Bill No. <b>${state.billNo}</b></span></div><div class="order-context"><span>${state.mode==='DINE IN'?`${state.area} · ${state.table}`:state.mode}</span><button onclick="selectArea()">Change</button></div><div class="order-label"><span>ITEMS</span><span>CHECKITEMS</span><span>QTY.</span><span>PRICE</span></div><div class="cart" id="cart">${cartHtml()}</div><div class="order-actions-row"><button onclick="addOrderNote()">＋ Note</button><button onclick="discountModal()">% Discount</button><button onclick="complimentary()">★ Complimentary</button></div><div class="bill-bottom"><div class="bill-line"><span>Subtotal</span><b>${money(subtotal())}</b></div><div class="bill-line"><span>Discount ${state.coupon?`(${esc(state.coupon)})`:''}</span><b>- ${money(state.discount)}</b></div><div class="bill-line"><span>GST 5%</span><b>${money(tax())}</b></div><div class="total-row"><span>Total</span><b>${money(total())}</b></div><div class="pay-row">${['Cash','Card','UPI','Due','Part'].map(x=>`<label><input type="radio" name="pay" ${state.payment===x?'checked':''} onchange="state.payment='${x}';render()"> ${x}</label>`).join('')}</div><div class="paid"><label><input id="paidCheck" type="checkbox"> It's Paid</label></div><div class="bill-actions"><button onclick="saveBill()">SAVE</button><button onclick="printBill(true)">SAVE & PRINT</button><button onclick="kot(false)">KOT</button><button onclick="kot(true)">KOT & PRINT</button></div></div></section></div>`;}
function filteredItems(){let arr=products.filter(p=>p.active);if(state.cat==='South Indian')arr=arr.filter(p=>p.cat==='South Indian');else if(state.cat==='Beverages')arr=arr.filter(p=>p.cat==='Beverages');else if(state.cat==='Indian Breads')arr=arr.filter(p=>p.cat==='Breads');else if(state.cat==='Rice')arr=arr.filter(p=>p.cat==='Rice');else if(state.cat==='Desserts')arr=arr.filter(p=>p.cat==='Desserts');else if(state.cat==='Starters'||state.cat==='Soups'||state.cat==='Meal Boxes')arr=arr.filter(p=>p.cat===state.cat);else if(state.cat==='Favorite Items')arr=arr.slice(0,18);if(state.search)arr=arr.filter(p=>p.name.toLowerCase().includes(state.search.toLowerCase()));return arr;}
function items(){return filteredItems().map(p=>`<button class="item" onclick="variants(${p.id})"><span class="veg-mark">●</span><strong>${esc(p.name)}</strong><small>₹${Math.min(...p.variants.map(v=>v[1]))}</small></button>`).join('')||'<div class="no-items">No items found</div>';}
function drawItems(){const g=document.getElementById('item-grid');if(g)g.innerHTML=items();}
function setCat(c){state.cat=c;state.search='';render();}
function setMode(m){state.mode=m;render();}
function variants(id){const p=products.find(x=>x.id===id);document.getElementById('modal').innerHTML=`<div class="shade"><div class="choice"><div class="choice-head"><div><span class="eyebrow">ADD TO ORDER</span><h3>${esc(p.name)}</h3></div><button onclick="closeModal()">×</button></div><p>Select portion, then optional extras.</p>${p.variants.map((v,i)=>`<button onclick="addonStep(${p.id},${i})"><span><b>${esc(v[0])}</b><small>Veg · ${esc(p.cat)}</small></span><b>${money(v[1])}</b></button>`).join('')}<button class="close" onclick="closeModal()">Cancel</button></div></div>`;}
function addonStep(id,i){const p=products.find(x=>x.id===id),v=p.variants[i];document.getElementById('modal').innerHTML=`<div class="shade"><div class="choice"><div class="choice-head"><div><span class="eyebrow">EXTRAS</span><h3>${esc(p.name)} · ${esc(v[0])}</h3></div><button onclick="closeModal()">×</button></div><div class="addon-list">${p.addons?.length?p.addons.map(a=>`<label><input type="checkbox" value="${esc(a)}"> ${esc(a)}</label>`).join(''):'<span class="muted">No add-ons configured</span>'}</div><textarea id="itemNote" placeholder="Kitchen note, e.g. less spicy / no onion"></textarea><button class="primary-wide" onclick="addConfigured(${p.id},${i})">Add to Bill · ${money(v[1])}</button></div></div>`;}
function addConfigured(id,i){const p=products.find(x=>x.id===id),v=p.variants[i],extras=[...document.querySelectorAll('.addon-list input:checked')].map(x=>x.value),note=(document.getElementById('itemNote')?.value||'').trim();const extraCost=extras.length*10;const key=extras.join('|')+'|'+note;const f=state.cart.find(x=>x.id===id&&x.variant===v[0]&&x.key===key);if(f)f.qty++;else state.cart.push({id,name:p.name,variant:v[0],price:v[1]+extraCost,qty:1,extras,note,key});closeModal();render();}
function cartHtml(){if(!state.cart.length)return '<div class="empty-cart">No Item Selected<br><small>Please Select Item from Left Menu Item</small><div class="plate">♨</div></div>';return state.cart.map((x,i)=>`<div class="cart-line"><div><b>${esc(x.name)}</b><small>${esc(x.variant)}${x.extras?.length?` · ${esc(x.extras.join(', '))}`:''}${x.note?` · ${esc(x.note)}`:''}</small></div><div class="qty"><button onclick="qty(${i},-1)">−</button><b>${x.qty}</b><button onclick="qty(${i},1)">+</button></div><strong>${money(x.price*x.qty)}<button class="remove-line" onclick="removeLine(${i})">×</button></strong></div>`).join('');}
function qty(i,n){state.cart[i].qty+=n;if(state.cart[i].qty<1)state.cart.splice(i,1);render();}
function removeLine(i){state.cart.splice(i,1);render();}
function subtotal(){return state.cart.reduce((s,x)=>s+x.price*x.qty,0);}
function discountModal(){document.getElementById('modal').innerHTML=`<div class="shade"><div class="dialog"><h3>Apply Discount / Coupon</h3><p>Demo controls for cashier discount handling.</p><div class="two-col"><label>Type<select id="discType"><option>Percentage</option><option>Flat</option></select></label><label>Value<input id="discValue" type="number" value="5"></label></div><label>Coupon Code<input id="coupon" placeholder="WELCOME5"></label><div class="dialog-actions"><button class="close" onclick="closeModal()">Cancel</button><button class="primary" onclick="applyDiscount()">Apply</button></div></div></div>`;}
function applyDiscount(){const type=document.getElementById('discType').value,val=Number(document.getElementById('discValue').value||0);state.discount=type==='Percentage'?Math.round(subtotal()*val/100):Math.min(val,subtotal());state.coupon=document.getElementById('coupon').value.trim();closeModal();render();}
function complimentary(){state.discount=subtotal();state.coupon='COMPLIMENTARY';render();}
function tax(){return Math.round((subtotal()-Math.min(state.discount,subtotal()))*.05);}
function total(){return Math.max(0,subtotal()-Math.min(state.discount,subtotal())+tax());}
function addOrderNote(){document.getElementById('modal').innerHTML=`<div class="shade"><div class="dialog"><h3>Order Note</h3><textarea id="orderNote" placeholder="e.g. Serve parcel separately, table needs extra plates"></textarea><div class="dialog-actions"><button class="close" onclick="closeModal()">Cancel</button><button class="primary" onclick="saveOrderNote()">Save</button></div></div></div>`;}
function saveOrderNote(){state.orderNote=(document.getElementById('orderNote')||{}).value||'';closeModal();}
function chooseTable(){const t=prompt('Enter table number',state.table);if(t){state.table=t.toUpperCase();render();}}
function selectArea(){const a=prompt('Area / section',state.area);if(a){state.area=a;render();}}
function chooseGuests(){const n=prompt('Number of guests','2');if(n)state.guests=n;}
function customerModal(){document.getElementById('modal').innerHTML=`<div class="shade"><div class="dialog"><h3>Customer</h3><label>Search mobile / name<input id="custSearch" placeholder="98765... or customer name"></label><div class="customer-list"><button onclick="setCustomer('Walk-in Customer')">Walk-in Customer</button><button onclick="setCustomer('Ramesh Kumar · 98XXXXXX12')">Ramesh Kumar · 124 pts</button><button onclick="setCustomer('Anita Rao · 63XXXXXX42')">Anita Rao · 88 pts</button></div><button class="close" onclick="closeModal()">Close</button></div></div>`;}
function setCustomer(x){state.customer=x;closeModal();render();}
function splitMerge(){document.getElementById('modal').innerHTML=`<div class="shade"><div class="dialog"><h3>Table / Bill Operations</h3><p>Typical cashier controls for fast restaurant service.</p><div class="quick-action-grid"><button onclick="alert('Demo: split bill by item')">Split by Item</button><button onclick="alert('Demo: split bill equally')">Split Equally</button><button onclick="alert('Demo: merge with another table')">Merge Table</button><button onclick="alert('Demo: transfer table')">Transfer Table</button></div><button class="close" onclick="closeModal()">Close</button></div></div>`;}
function saveBill(){if(!state.cart.length)return alert('Add items before saving the bill.');state.billNo++;localStorage.setItem('varahi_bill',state.billNo);alert(`Bill #${state.billNo-1} saved.`);}
function newBill(){state.cart=[];state.discount=0;state.coupon='';state.customer=null;state.billNo++;localStorage.setItem('varahi_bill',state.billNo);state.mode='DINE IN';render();}
function kot(printToo){if(!state.cart.length)return alert('Add items before sending KOT.');const msg=`KOT #${state.billNo} sent to kitchen for ${state.mode==='DINE IN'?state.table:state.mode}.`;if(printToo){alert(msg+'\nKOT print queued.');}else alert(msg);}
function printBill(saveFirst){if(!state.cart.length)return alert('Add items before printing.');if(saveFirst)saveBill();const rows=state.cart.map(x=>`<div><span>${esc(x.name)}<small>${esc(x.variant)} × ${x.qty}</small></span><b>${money(x.price*x.qty)}</b></div>`).join('');document.getElementById('modal').innerHTML=`<div class="shade print-shade"><div class="receipt"><div class="receipt-head"><b>VARAHI BILLING SOFTWARE</b><small>Restaurant POS</small></div><p>**** · ****</p><hr>${rows}<hr><div class="receipt-row"><span>Subtotal</span><b>${money(subtotal())}</b></div><div class="receipt-row"><span>Discount</span><b>- ${money(state.discount)}</b></div><div class="receipt-row"><span>GST 5%</span><b>${money(tax())}</b></div><div class="receipt-row total"><span>TOTAL</span><b>${money(total())}</b></div><p>${state.mode==='DINE IN'?`Table ${state.table} · `:''}${state.payment}</p><p>${state.customer||'Walk-in Customer'}</p><p>Thank you for visiting</p><button onclick="window.print()">PRINT THERMAL BILL</button><button onclick="closeModal()">CLOSE</button></div></div>`;}
function showQR(){document.getElementById('modal').innerHTML=`<div class="shade"><div class="qr-card"><h3>QR Ordering</h3><div class="fake-qr">▦<br>QR</div><p>Table QR: ${state.table}</p><small>Customer scans → sees vegetarian menu → sends order to POS.</small><button class="primary-wide" onclick="closeModal()">Done</button></div></div>`;}
function showSupport(){alert('Varahi Support Demo · Phone **** · 24×7 support workflow placeholder.');}
function moduleView(v){const pages={dashboard:dashboardPage,tables:tablesPage,menu:menuPage,inventory:inventoryPage,crm:crmPage,accounting:accountingPage,reports:reportsPage,config:configPage,users:usersPage,online:onlinePage,kitchen:kitchenPage,pos:()=>posView()};return pages[v]?pages[v]():posView();}
function moduleHeader(k,title,desc,action=''){return `<div class="module-page-head"><div><span class="eyebrow">${k.toUpperCase()}</span><h2>${title}</h2><p>${desc}</p></div>${action?`<button class="primary" onclick="${action}">＋ ${k==='menu'?'ADD PRODUCT':action.includes('purchase')?'NEW PURCHASE':'NEW'}</button>`:''}</div>`;}
function dashboardPage(){return `<div class="module-page">${moduleHeader('Dashboard','Restaurant Overview','Today at a glance.')}<div class="dash-cards"><div><span>Gross Sales</span><b>₹24,680</b><small>86 bills</small></div><div><span>Open Orders</span><b>12</b><small>4 online</small></div><div><span>Guests Served</span><b>214</b><small>Today</small></div><div><span>Low Stock</span><b>7</b><small>Items need attention</small></div></div><div class="dashboard-grid"><div class="panel-card"><h3>Order Flow</h3><div class="flow"><span>Order Taken</span><i>→</i><span>KOT</span><i>→</i><span>Kitchen</span><i>→</i><span>Bill</span><i>→</i><span>Paid</span></div><div class="mini-table"><div><b>Top items</b><span>Qty</span><span>Sales</span></div>${[['Masala Dosa','34','₹3,060'],['Idli Vada','29','₹2,030'],['Veg Meals','21','₹3,360'],['Filter Coffee','38','₹1,710']].map(r=>`<div><span>${r[0]}</span><span>${r[1]}</span><span>${r[2]}</span></div>`).join('')}</div></div><div class="panel-card"><h3>Payment Summary</h3>${[['Cash','₹8,420'],['UPI','₹11,280'],['Card','₹4,980']].map(r=>`<div class="metric-row"><span>${r[0]}</span><b>${r[1]}</b></div>`).join('')}<hr><div class="metric-row"><span>Pending Due</span><b>₹1,240</b></div></div></div></div>`;}
function tablesPage(){return `<div class="module-page">${moduleHeader('Tables','Table Management','Areas, live table status and bill controls.','newBill()')}<div class="area-tabs"><button class="active">Main Hall</button><button>AC Hall</button><button>Outdoor</button><button>Family</button></div><div class="table-board">${Array.from({length:20},(_,i)=>{const n=i+1,status=n%5===0?'BILLING':n%3===0?'AVAILABLE':'OCCUPIED';return `<button class="floor-table ${status.toLowerCase()}" onclick="state.view='pos';state.table='T${String(n).padStart(2,'0')}';render()"><b>T${String(n).padStart(2,'0')}</b><span>${status}</span><small>${status==='AVAILABLE'?'Ready':status==='BILLING'?'Bill open':`${(n%4)+1} guests`}</small></button>`}).join('')}</div></div>`;}
function menuPage(){return `<div class="module-page">${moduleHeader('menu','Menu Management','Products, portions, add-ons and online availability.','openProductForm()')}<div class="subtabs"><button class="active">Items</button><button>Categories</button><button>Add-ons</button><button>Recipes</button><button>Online Menu</button></div><div class="data-card"><table><thead><tr><th>Item</th><th>Category</th><th>Portions</th><th>Online</th><th>Stock</th><th>Actions</th></tr></thead><tbody>${products.map(p=>`<tr><td><span class="veg-mark">●</span><b>${esc(p.name)}</b></td><td>${esc(p.cat)}</td><td>${p.variants.map(v=>`${esc(v[0])} ${money(v[1])}`).join(' · ')}</td><td><span class="pill green-pill">ON</span></td><td><span class="pill ${p.id%4===0?'amber-pill':'green-pill'}">${p.id%4===0?'LOW':'OK'}</span></td><td><button onclick="openProductForm(${p.id})">Edit</button><button onclick="deleteProduct(${p.id})">Delete</button></td></tr>`).join('')}</tbody></table></div></div>`;}
function openProductForm(id=null){const p=id?products.find(x=>x.id===id):{name:'',cat:'South Indian',price:'',variants:[['Regular','']],addons:['Extra Sambar'],active:true};document.getElementById('modal').innerHTML=`<div class="shade"><div class="dialog wide"><h3>${id?'Edit':'Add'} Product</h3><div class="two-col"><label>Product Name<input id="pn" value="${esc(p.name)}"></label><label>Category<select id="pc">${['South Indian','Breakfast','Meals','North Indian','Breads','Rice','Beverages','Desserts','Starters','Soups'].map(c=>`<option ${c===p.cat?'selected':''}>${c}</option>`).join('')}</select></label><label>Base Price<input id="pp" type="number" value="${p.price||''}"></label><label>Portion / Size<input id="pv" value="${esc(p.variants[0]?.[0]||'Regular')}"></label></div><label>Add-ons (comma separated)<input id="pa" value="${esc((p.addons||[]).join(', '))}"></label><div class="dialog-actions"><button class="close" onclick="closeModal()">Cancel</button><button class="primary" onclick="saveProduct(${id||0})">Save Product</button></div></div></div>`;}
function saveProduct(id){const name=document.getElementById('pn').value.trim(),cat=document.getElementById('pc').value,price=Number(document.getElementById('pp').value),portion=document.getElementById('pv').value.trim(),addons=document.getElementById('pa').value.split(',').map(x=>x.trim()).filter(Boolean);if(!name||!price||!portion)return alert('Enter product name, price and portion.');if(id){const p=products.find(x=>x.id===id);Object.assign(p,{name,cat,price,variants:[[portion,price]],addons,active:true});}else products.push({id:Date.now(),name,cat,price,variants:[[portion,price]],addons,active:true});save();closeModal();render();}
function deleteProduct(id){if(confirm('Delete this product?')){products=products.filter(p=>p.id!==id);save();render();}}
function inventoryPage(){const rows=[['Rice','kg','38','50','Reorder at 50kg'],['Urad Dal','kg','14','25','Low'],['Coffee Powder','kg','6','10','Low'],['Milk','L','32','40','Monitor'],['Curd','kg','9','15','Low'],['Paneer','kg','18','20','Monitor'],['Cooking Oil','L','21','25','Monitor']];return `<div class="module-page">${moduleHeader('inventory','Inventory Management','Stock, low-stock alerts, purchases and consumption.','newPurchase()')}<div class="dash-cards"><div><span>Stock Value</span><b>₹1.82L</b><small>Current</small></div><div><span>Low Stock</span><b>7</b><small>Needs reorder</small></div><div><span>Purchase Today</span><b>₹18,420</b><small>3 suppliers</small></div><div><span>Food Cost</span><b>31.2%</b><small>This month</small></div></div><div class="data-card"><table><thead><tr><th>Raw Material</th><th>Unit</th><th>Current</th><th>Par Level</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td><span class="pill ${r[2]<r[3]?'amber-pill':'green-pill'}">${r[4]}</span></td><td><button onclick="alert('Purchase order draft created')">Reorder</button></td></tr>`).join('')}</tbody></table></div></div>`;}
function newPurchase(){alert('Demo: Purchase order / GRN workflow opened.');}
function crmPage(){return `<div class="module-page">${moduleHeader('crm','Customer Management','Profiles, labels, loyalty and campaign-ready customer data.','addCustomer()')}<div class="subtabs"><button class="active">Customers</button><button>Labels</button><button>Loyalty</button><button>Campaigns</button></div><div class="data-card"><table><thead><tr><th>Customer</th><th>Visits</th><th>Spend</th><th>Points</th><th>Last Visit</th><th>Label</th></tr></thead><tbody>${[['Ramesh Kumar','18','₹12,840','124','Today','Regular'],['Anita Rao','12','₹8,760','88','Yesterday','Family'],['Suresh Babu','7','₹4,420','42','3 days ago','New'],['Kavya P','28','₹21,140','312','Today','VIP']].map(r=>`<tr><td><b>${r[0]}</b><small>98XXXXXX12</small></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td><td><span class="pill green-pill">${r[5]}</span></td></tr>`).join('')}</tbody></table></div></div>`;}
function addCustomer(){alert('Demo: Customer registration / OTP workflow.');}
function accountingPage(){return `<div class="module-page">${moduleHeader('accounting','Accounting','Cash drawer, expenses, dues and business summary.')}<div class="dash-cards"><div><span>Opening Cash</span><b>₹10,000</b><small>Today</small></div><div><span>Cash Sales</span><b>₹8,420</b><small>Today</small></div><div><span>Expenses</span><b>₹2,140</b><small>Today</small></div><div><span>Cash In Drawer</span><b>₹16,280</b><small>Expected</small></div></div><div class="dashboard-grid"><div class="panel-card"><h3>Expenses</h3><div class="metric-row"><span>Vegetables & groceries</span><b>₹1,120</b></div><div class="metric-row"><span>Cleaning</span><b>₹420</b></div><div class="metric-row"><span>Miscellaneous</span><b>₹600</b></div><button class="secondary wide-btn" onclick="alert('Demo: add expense')">+ Add Expense</button></div><div class="panel-card"><h3>Business Snapshot</h3><div class="metric-row"><span>Sales</span><b>₹24,680</b></div><div class="metric-row"><span>Purchases</span><b>₹18,420</b></div><div class="metric-row"><span>Operating Expenses</span><b>₹2,140</b></div><div class="metric-row"><span>Estimated Margin</span><b>₹4,120</b></div></div></div></div>`;}
function reportsPage(){return `<div class="module-page">${moduleHeader('reports','Reports & Analytics','Sales, tax, payment, item, KOT and staff reports.')}<div class="report-tabs">${['Sales Summary','Item Wise','Payment','GST','Discount','KOT','Staff','Online Orders'].map((x,i)=>`<button class="${i===0?'active':''}">${x}</button>`).join('')}</div><div class="dash-cards"><div><span>Gross Sales</span><b>₹24,680</b><small>86 bills</small></div><div><span>Average Order</span><b>₹287</b><small>Today</small></div><div><span>Discounts</span><b>₹1,140</b><small>4.6%</small></div><div><span>Tax Collected</span><b>₹1,176</b><small>GST</small></div></div><div class="dashboard-grid"><div class="panel-card"><h3>Category Sales</h3>${[['South Indian',84],['Meals',62],['Beverages',41],['North Indian',37]].map(x=>`<div class="report-bar"><div><span>${x[0]}</span><b>${x[1]}%</b></div><div><i style="width:${x[1]}%"></i></div></div>`).join('')}</div><div class="panel-card"><h3>Quick Exports</h3><button class="secondary wide-btn" onclick="alert('Sales CSV export generated')">Export Sales CSV</button><button class="secondary wide-btn" onclick="alert('GST report generated')">Export GST Report</button><button class="secondary wide-btn" onclick="alert('P&L preview opened')">Preview P&L</button></div></div></div>`;}
function configPage(){return `<div class="module-page">${moduleHeader('config','Configuration','Taxes, printers, billing preferences, order types and outlet settings.')}<div class="settings-grid"><div class="panel-card"><h3>Business Profile</h3>${[['Software','Varahi Billing Software'],['Address','****'],['Phone','****'],['GSTIN','****'],['Currency','INR (₹)']].map(x=>`<div class="metric-row"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div><div class="panel-card"><h3>Billing & Printer</h3>${[['Thermal Paper','80mm'],['KOT Printer','Enabled'],['Bill Printer','TVS Thermal'],['GST','5% demo'],['Offline Mode','Enabled']].map(x=>`<div class="metric-row"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}<button class="secondary wide-btn" onclick="testPrinter()">Test Printer</button></div><div class="panel-card"><h3>Order Types</h3><div class="check-list">${['Dine In','Delivery','Pick Up','Online Orders','QR Ordering'].map(x=>`<label><input type="checkbox" checked> ${x}</label>`).join('')}</div></div><div class="panel-card"><h3>Menu Controls</h3><div class="check-list">${['Stock based online menu','Auto low stock alert','Recipe based deduction','Multiple portions','Add-ons / modifiers'].map(x=>`<label><input type="checkbox" checked> ${x}</label>`).join('')}</div></div></div></div>`;}
function testPrinter(){alert('Demo printer test sent to TVS thermal printer queue.');}
function usersPage(){return `<div class="module-page">${moduleHeader('users','User Management','Rights, biller controls and staff access.','addUser()')}<div class="data-card"><table><thead><tr><th>Name</th><th>Role</th><th>POS</th><th>KOT</th><th>Inventory</th><th>Reports</th><th>Status</th></tr></thead><tbody>${[['Amit','Owner','Full','Full','Full','Full'],['Ravi','Manager','Full','Full','Full','View'],['Pooja','Cashier','Bill','KOT','No','View'],['Chef Anand','Kitchen','No','Full','View','No']].map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td><td>${r[5]}</td><td><span class="pill green-pill">Active</span></td></tr>`).join('')}</tbody></table></div></div>`;}
function addUser(){alert('Demo: New staff account / role rights.');}
function onlinePage(){return `<div class="module-page">${moduleHeader('online','Online Orders','One screen for delivery, pick-up and aggregator orders.')}<div class="report-tabs"><button class="active">All</button><button>Swiggy</button><button>Zomato</button><button>QR Order</button><button>Web</button></div><div class="online-grid">${[['#SWT-4032','Swiggy','New','₹420'],['#ZMT-7194','Zomato','Preparing','₹560'],['#QR-2811','QR Order','Ready','₹310'],['#WEB-1820','Website','New','₹760']].map(o=>`<div class="online-card"><div><b>${o[0]}</b><span class="source">${o[1]}</span></div><span class="status-pill">${o[2]}</span><strong>${o[3]}</strong><p>2× Idli Vada, 1× Masala Dosa, 2× Filter Coffee</p><div><button onclick="alert('KOT generated for '+ '${o[0]}')">Print KOT</button><button onclick="alert('Bill marked ready')">Mark Ready</button></div></div>`).join('')}</div></div>`;}
function kitchenPage(){const ks=[['KOT #1021','T04','Masala Dosa × 2, Filter Coffee × 2','Preparing'],['KOT #1022','T02','Idli Vada × 2, Vada × 1','Ready'],['KOT #1023','Takeaway','Veg Meals × 1, Lime Soda × 2','New'],['KOT #1024','QR Order','South Indian Thali × 2','Preparing']];return `<div class="module-page">${moduleHeader('kitchen','Kitchen Display / KOT','Live tickets, prep timers and ready status.')}<div class="kitchen-board">${ks.map((x,i)=>`<div class="k-card"><div class="k-top"><b>${x[0]}</b><span class="k-status ${x[3].toLowerCase()}">${x[3]}</span></div><strong>${x[1]}</strong><p>${x[2]}</p><div class="k-bottom"><small>${2+i*3} min ago</small><button onclick="alert('${x[0]} marked ready')">Mark Ready</button></div></div>`).join('')}</div></div>`;}
render();
